services:
  backend:
    build: .
    image: liquordb-backend:latest
    networks:
      - liquordb-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    env_file:
      - .env
    working_dir: /backend
    volumes:
      - backend_uploads:/backend/uploads # 업로드 파일 영속성 확보
      -
networks:
  liquordb-network:
    driver: bridge

volumes:
  backend_uploads:
  mysql_data:
  redis-data: