package com.liquordb.enums;

public enum ErrorCode {

    // TODO 수정필요
    LOGIN_FAILED,
    UNAUTHENTICATED_USER, // 인증 정보 충족 실패
    ACCESS_DENIED, // 인가 정보 충족 실패,

    // User
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    DUPLICATE_USER,
    SUSPENDED_USER, // 활동제한
    BANNED_USER, // 강제탈퇴

    // Liquor
    LIQUOR_NOT_FOUND,
    LIQUOR_ALREADY_EXISTS,

    // Review
    REVIEW_NOT_FOUND,
    REVIEW_ALREADY_EXISTS,

    // Comment
    COMMENT_NOT_FOUND,
    INVALID_PARENT_COMMENT,

    // Tag
    TAG_NOT_FOUND,
    TAG_ALREADY_EXISTS,
    USER_TAG_NOT_FOUND,
    USER_TAG_ALREADY_EXISTS,
    LIQUID_NOT_FOUND,
    LIQUOR_TAG_ALREADY_EXISTS,

    // Report
    COMMENT_REPORT_NOT_FOUND,
    COMMENT_REPORT_ALREADY_EXISTS,
    REVIEW_REPORT_NOT_FOUND,
    REVIEW_REPORT_ALREADY_EXISTS,

    // Notice
    NOTICE_NOT_FOUND,

    // File
    BINARY_CONTENT_NOT_FOUND,
    DUPLICATE_BINARY_CONTENT,
    BINARY_CONTENT_UPLOAD_ALREADY_SUCCEEDED,

    NOTIFICATION_NOT_FOUND,

    VALIDATION_FAILED;
}
